# Change these first
owner: T-SOLUTION-VIETNAM-CORPORATION # Your GitHub organization or username, where this repository lives
repo: tsolution-status-check-20230509 # The name of this repository

sites:
  - name: Beripharma
    url: https://beripharma.com
  - name: Maxhouse
    url: https://maxhousevietnam.com
  - name: Trinix
    url: https://trinix.studio
  - name: TPC
    url: https://thaiphong.vn
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /tsolution-status-check-20230509
  logoUrl: https://avatars.githubusercontent.com/u/95016283?s=200&v=4
  name: T-solution
  introTitle: "Status Check"
  introMessage: "Welcome to Tsolution's Status Website! We understand the importance of reliable and uninterrupted services in today's fast-paced digital landscape. With our Status Website, we provide real-time updates on the operational status of our systems, ensuring transparency and peace of mind for our valued clients. Stay informed and stay connected as we strive to deliver seamless experiences and maintain optimal performance."

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
